version: 2.1
orbs:
  node: circleci/node@5.0.3
  eb: circleci/aws-elastic-beanstalk@2.0.1

jobs:
  install-packages:
    executor: node/default # use the default executor defined within the orb
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm

  deploy:
    docker:
      - image: "cimg/base:stable"
    steps:
#      - node/install:
 #         node-version: '14.15' 
      - eb/setup
  #    - aws-cli/setup
      - checkout
      - run:
          name: Deploy App
          # TODO: Install, build, deploy in both apps
          command: |
            eb use node-express-env
            eb deploy
            
workflows:
  example-workflow:
    jobs:
      - install-packages
      - deploy