version: 2.1
orbs:
  node: circleci/node@5.0.3
jobs:
  example-job:
    executor: node/default # use the default executor defined within the orb
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      
      - run:
          name: ls
          command: ls
workflows:
  example-workflow:
    jobs:
      - example-job